### ISSUE TITLE
Google Photos APIへのリクエスト方法

### ISSUE THREAD

**Issue by niemuuu** [LiberoTech/VideoManager#2]
- どの単位でAPIにリクエストを送る？
  - 全件？５件ずつ？

- スクロールに合わせて少しずつ動画を取得できる？

**Comment by kazuki-n** [comment]
まずは動画リスト
batchgetでIDsをparameterに指定して複数の動画を取得するリクエストを送ることができそう。

**Comment by niemuuu** [comment]
mediaItemId:`iuoihiio` `roqi3jrj32oi` を指定する場合のreq

GET https://photoslibrary.googleapis.com/v1/mediaItems:batchGet?mediaItemIds=iuoihiio&mediaItemIds=roqi3jrj32oi HTTP/1.1

Authorization: Bearer [YOUR_ACCESS_TOKEN]
Accept: application/json

**Comment by kazuki-n** [comment]
■レスポンスはどんな感じでかえってくる？

**Comment by niemuuu** [comment]
https://developers.google.com/photos/library/reference/rest/v1/mediaItems#MediaItem
