### ISSUE TITLE
google photos 動画URLのAPIをたたける状態にする。

### ISSUE THREAD

**Issue by kazuki-n** [LiberoTech/VideoManager#3]
# ゴール
- 直に動画URL取得のリクエスト叩けてかつレスポンスが正常に返ってくる

# 主なタスク
- アカウント作成
- APIキー取得？

**Comment by kazuki-n** [comment]
- Google Photos API for Laravel
- 主に準備手順の参照
    - https://qiita.com/kawax/items/65fc695a972d764d449f

**Comment by kazuki-n** [comment]
https://developers.google.com/photos/library/guides/get-started

**Comment by kazuki-n** [comment]
https://developers.google.com/photos/library/samples

**Comment by kazuki-n** [comment]
## 次にやること
- 以下の画面のexecuterからリクエストを送り正常にレスポンスが返ってくることを確認する。（ここから叩く感じでアプリからリクエストをおくればOKになる想定）
https://developers.google.com/photos/library/reference/rest/v1/albums/get?hl=ja

**Comment by kazuki-n** [comment]
https://int128.hatenablog.com/entry/2018/06/06/234653

**Comment by kazuki-n** [comment]
http://ytyaru.hatenablog.com/entry/2017/02/06/000000

**Comment by kazuki-n** [comment]
Example (CustomHTTP)
Code:
```
ctx := context.Background()

conf := &oauth2.Config{
    ClientID:     "YOUR_CLIENT_ID",
    ClientSecret: "YOUR_CLIENT_SECRET",
    Scopes:       []string{"SCOPE1", "SCOPE2"},
    Endpoint: oauth2.Endpoint{
        TokenURL: "https://provider.com/o/oauth2/token",
        AuthURL:  "https://provider.com/o/oauth2/auth",
    },
}

// Redirect user to consent page to ask for permission
// for the scopes specified above.
url := conf.AuthCodeURL("state", oauth2.AccessTypeOffline)
fmt.Printf("Visit the URL for the auth dialog: %v", url)

// Use the authorization code that is pushed to the redirect
// URL. Exchange will do the handshake to retrieve the
// initial access token. The HTTP Client returned by
// conf.Client will refresh the token as necessary.
var code string
if _, err := fmt.Scan(&code); err != nil {
    log.Fatal(err)
}

// Use the custom HTTP client when requesting a token.
httpClient := &http.Client{Timeout: 2 * time.Second}
ctx = context.WithValue(ctx, oauth2.HTTPClient, httpClient)

tok, err := conf.Exchange(ctx, code)
if err != nil {
    log.Fatal(err)
}

client := conf.Client(ctx, tok)
_ = client
```

**Comment by kazuki-n** [comment]
# Googleフォトに写真をアップロードするツールを作った
- https://int128.hatenablog.com/entry/2018/06/16/132842

**Comment by niemuuu** [comment]
[Heroku上からService Account認証でGoogle APIにアクセスする](https://memo.sugyan.com/entry/20130112/1357996092)

**Comment by kazuki-n** [comment]
## 結局どうしたか
- まずAuthはサービスアカウントは使わない。Authクライアントを使う。
- 起動前にauthcodeを環境変数にセットしてからgoを起動する。
