### ISSUE TITLE
ミニマムのLINE Bot作成（初期設定〜Hello World）

### ISSUE THREAD

**Issue by kazuki-n** [LiberoTech/VideoManager#4]
# ゴール
- LINEのトーク画面に作ったbotがあわわれるまで。

# 主なタスク
- [x] 誰のアカウントで作るか検討(LINE@とかのアカウントでは無理？)
- [x] プロバイダ作ったりなど
- [x] ローカルで動かす
- [x] herokuにデプロイ
- [x] 環境変数をherokuで設定する

**Comment by kazuki-n** [comment]
ともき作ったプロバイダを使う
初期設定もこのissueでやっちゃう

**Comment by kazuki-n** [comment]
- line developersにログイン
- プロバイダの作成
- アクセストークン発行

**Comment by kazuki-n** [comment]
linebotのプログラムをどこで動かす？
- go on heroku
- botのプログラムだけ別の場所で動かす。

## 結論
- now.shでgoを動かす方向で進める
    - line bot と view app でアプリプロセスを分けたほうが綺麗でnow.shでgoを動かすのもともき的にはコストはそんなにかからない
    - できればGoで処理を描きたい。

**Comment by niemuuu** [comment]
LINE bot with Go 参考
https://qiita.com/sao_rio/items/8801b78ba60acbb0ae41

**Comment by niemuuu** [comment]
ローカル動作で詰まったポイント
- webhookを使う、をチェックしていなかった（LINE developer側の設定）
- line bot側のwebhook urlに `/callback` をつけ忘れていた

**Comment by niemuuu** [comment]
ミニマムのLINE Botコミット:https://github.com/LiberoTech/VideoManager/commit/95636c895e4774e32f060efdb529f9b09e2579f3
